// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDERxiYyu3ibyZD_ikpc4GvSezEXBazqbw',
    appId: '1:780593325258:web:e2e1a0c18a8a0c51a74033',
    messagingSenderId: '780593325258',
    projectId: 'e-commerce-151db',
    authDomain: 'e-commerce-151db.firebaseapp.com',
    storageBucket: 'e-commerce-151db.appspot.com',
    measurementId: 'G-Z9RG11TW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOvbmmBTMAsGuIcodha-EatV-QChFVwA',
    appId: '1:780593325258:android:6f2f4cc67c941050a74033',
    messagingSenderId: '780593325258',
    projectId: 'e-commerce-151db',
    storageBucket: 'e-commerce-151db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMPhPC1DyNoq370kjWqk2dbh-2qB7TmQ',
    appId: '1:780593325258:ios:7e05a21fda306849a74033',
    messagingSenderId: '780593325258',
    projectId: 'e-commerce-151db',
    storageBucket: 'e-commerce-151db.appspot.com',
    androidClientId: '780593325258-frfojitm0ku45o2upkaqol3iidp7512v.apps.googleusercontent.com',
    iosClientId: '780593325258-pe8a62m1vinrl9ktj5269c6iv8iq22j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartBliss',
  );

}